[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
  type = "archive"
  url = "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
  exact = true
  stripComponents = 1
[ ".vim/bundle/Vundle.vim" ]
  type = "file"
  url = "https://github.com/VundleVim/Vundle.vim.git"
  refreshPeriod = "168h"
[ ".hammerspoon/Spoons/VimMode.spoons"]
  type = "file"
  url = "https://github.com/dbalatero/VimMode.spoon"
