#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -fv -B 0 -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/git-template/commit_template.txt" "/Users/stephane.liu/.git-template/commit_template.txt"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/git-template/hooks/lolcommits" "/Users/stephane.liu/.git-template/hooks/lolcommits"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/git-template/hooks/post-checkout" "/Users/stephane.liu/.git-template/hooks/post-checkout"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/git-template/hooks/post-commit" "/Users/stephane.liu/.git-template/hooks/post-commit"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/git-template/hooks/post-merge" "/Users/stephane.liu/.git-template/hooks/post-merge"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/git-template/hooks/post-rewrite" "/Users/stephane.liu/.git-template/hooks/post-rewrite"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/git-template/hooks/pre-commit" "/Users/stephane.liu/.git-template/hooks/pre-commit"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/git-template/hooks/pre-rebase" "/Users/stephane.liu/.git-template/hooks/pre-rebase"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/gitattributes" "/Users/stephane.liu/.gitattributes"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/gitconfig" "/Users/stephane.liu/.gitconfig"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/gitignore" "/Users/stephane.liu/.gitignore"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/vim/rcplugins/conflicted.vim" "/Users/stephane.liu/.vim/rcplugins/conflicted.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/vim/rcplugins/endwise.vim" "/Users/stephane.liu/.vim/rcplugins/endwise.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/vim/rcplugins/fugitive.vim" "/Users/stephane.liu/.vim/rcplugins/fugitive.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/vim/rcplugins/gist.vim" "/Users/stephane.liu/.vim/rcplugins/gist.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/vim/rcplugins/git.vim" "/Users/stephane.liu/.vim/rcplugins/git.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/vim/rcplugins/gitgutter.vim" "/Users/stephane.liu/.vim/rcplugins/gitgutter.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/vim/rcplugins/nvim_blame_line.vim" "/Users/stephane.liu/.vim/rcplugins/nvim_blame_line.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/vim/rcplugins/vim_gh_line.vim" "/Users/stephane.liu/.vim/rcplugins/vim_gh_line.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/zsh/after/completion.zsh" "/Users/stephane.liu/.zsh/after/completion.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/zsh/git.zsh" "/Users/stephane.liu/.zsh/git.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-git/zsh/lol.zsh" "/Users/stephane.liu/.zsh/lol.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/default-gems" "/Users/stephane.liu/.default-gems"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/editrc" "/Users/stephane.liu/.editrc"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/gemrc" "/Users/stephane.liu/.gemrc"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/irbrc" "/Users/stephane.liu/.irbrc"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/pryrc" "/Users/stephane.liu/.pryrc"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/railsrc" "/Users/stephane.liu/.railsrc"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/rdebugrc" "/Users/stephane.liu/.rdebugrc"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/vim/rcplugins/ale_ruby.vim" "/Users/stephane.liu/.vim/rcplugins/ale_ruby.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/vim/rcplugins/bundler.vim" "/Users/stephane.liu/.vim/rcplugins/bundler.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/vim/rcplugins/haml.vim" "/Users/stephane.liu/.vim/rcplugins/haml.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/vim/rcplugins/projectionist.vim" "/Users/stephane.liu/.vim/rcplugins/projectionist.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/vim/rcplugins/rails.vim" "/Users/stephane.liu/.vim/rcplugins/rails.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/vim/rcplugins/rake.vim" "/Users/stephane.liu/.vim/rcplugins/rake.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/vim/rcplugins/rspec.vim" "/Users/stephane.liu/.vim/rcplugins/rspec.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/vim/rcplugins/rubocop.vim" "/Users/stephane.liu/.vim/rcplugins/rubocop.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/vim/rcplugins/ruby.vim" "/Users/stephane.liu/.vim/rcplugins/ruby.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/vim/rcplugins/ruby_refactoring.vim" "/Users/stephane.liu/.vim/rcplugins/ruby_refactoring.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/vim/rcplugins/syntastic_ruby.vim" "/Users/stephane.liu/.vim/rcplugins/syntastic_ruby.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/vim/rcplugins/vim-rspec.vim" "/Users/stephane.liu/.vim/rcplugins/vim-rspec.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/vim/ruby_abbreviations.vim" "/Users/stephane.liu/.vim/ruby_abbreviations.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-ruby/zsh/ruby.zsh" "/Users/stephane.liu/.zsh/ruby.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-tmux/tmux.conf" "/Users/stephane.liu/.tmux.conf"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-tmux/vim/rcplugins/tmux.vim" "/Users/stephane.liu/.vim/rcplugins/tmux.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/tag-tmux/zsh/tmux.zsh" "/Users/stephane.liu/.zsh/tmux.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/Brewfile" "/Users/stephane.liu/Brewfile"
handle_file_ln "/Users/stephane.liu/.dotfiles/Brewfile.lock.json" "/Users/stephane.liu/.Brewfile.lock.json"
handle_file_ln "/Users/stephane.liu/.dotfiles/agignore" "/Users/stephane.liu/.agignore"
handle_file_ln "/Users/stephane.liu/.dotfiles/bin/24-bit-colors-test.sh" "/Users/stephane.liu/bin/24-bit-colors-test.sh"
handle_file_ln "/Users/stephane.liu/.dotfiles/bin/256-colors.sh" "/Users/stephane.liu/bin/256-colors.sh"
handle_file_ln "/Users/stephane.liu/.dotfiles/bin/link_rails_intellisense" "/Users/stephane.liu/bin/link_rails_intellisense"
handle_file_ln "/Users/stephane.liu/.dotfiles/bin/plist" "/Users/stephane.liu/bin/plist"
handle_file_ln "/Users/stephane.liu/.dotfiles/bin/psgrep" "/Users/stephane.liu/bin/psgrep"
handle_file_ln "/Users/stephane.liu/.dotfiles/bin/ray" "/Users/stephane.liu/bin/ray"
handle_file_ln "/Users/stephane.liu/.dotfiles/bin/silence_ruby" "/Users/stephane.liu/bin/silence_ruby"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/cheat/cheatsheets/personal/ruby" "/Users/stephane.liu/.config/cheat/cheatsheets/personal/ruby"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/cheat/conf.yml" "/Users/stephane.liu/.config/cheat/conf.yml"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/gitui/key_config.ron" "/Users/stephane.liu/.config/gitui/key_config.ron"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/current-theme.conf" "/Users/stephane.liu/.config/kitty/current-theme.conf"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/font.conf" "/Users/stephane.liu/.config/kitty/font.conf"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/grab.conf" "/Users/stephane.liu/.config/kitty/grab.conf"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/hints.conf" "/Users/stephane.liu/.config/kitty/hints.conf"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/kitty.conf" "/Users/stephane.liu/.config/kitty/kitty.conf"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/kitty_grab/LICENSE" "/Users/stephane.liu/.config/kitty/kitty_grab/LICENSE"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/kitty_grab/_grab_ui.py" "/Users/stephane.liu/.config/kitty/kitty_grab/_grab_ui.py"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/kitty_grab/grab-vim.conf.example" "/Users/stephane.liu/.config/kitty/kitty_grab/grab-vim.conf.example"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/kitty_grab/grab.conf.example" "/Users/stephane.liu/.config/kitty/kitty_grab/grab.conf.example"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/kitty_grab/grab.py" "/Users/stephane.liu/.config/kitty/kitty_grab/grab.py"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/kitty_grab/kitten_options_definition.py" "/Users/stephane.liu/.config/kitty/kitty_grab/kitten_options_definition.py"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/kitty_grab/kitten_options_parse.py" "/Users/stephane.liu/.config/kitty/kitty_grab/kitten_options_parse.py"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/kitty_grab/kitten_options_types.py" "/Users/stephane.liu/.config/kitty/kitty_grab/kitten_options_types.py"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/kitty_grab/kitten_options_utils.py" "/Users/stephane.liu/.config/kitty/kitty_grab/kitten_options_utils.py"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/kitty_grab/kitty.conf.example" "/Users/stephane.liu/.config/kitty/kitty_grab/kitty.conf.example"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/scrollback.conf" "/Users/stephane.liu/.config/kitty/scrollback.conf"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/splits.conf" "/Users/stephane.liu/.config/kitty/splits.conf"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/tabs.conf" "/Users/stephane.liu/.config/kitty/tabs.conf"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/theme.conf" "/Users/stephane.liu/.config/kitty/theme.conf"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/themes/solarized-dark.conf" "/Users/stephane.liu/.config/kitty/themes/solarized-dark.conf"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/themes/solarized-light.conf" "/Users/stephane.liu/.config/kitty/themes/solarized-light.conf"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/kitty/visual.conf" "/Users/stephane.liu/.config/kitty/visual.conf"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/nvim/init.vim" "/Users/stephane.liu/.config/nvim/init.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/config/tmuxinator/cc.yml" "/Users/stephane.liu/.config/tmuxinator/cc.yml"
handle_file_ln "/Users/stephane.liu/.dotfiles/ctags" "/Users/stephane.liu/.ctags"
handle_file_ln "/Users/stephane.liu/.dotfiles/dir_colors" "/Users/stephane.liu/.dir_colors"
handle_file_ln "/Users/stephane.liu/.dotfiles/inputrc" "/Users/stephane.liu/.inputrc"
handle_file_ln "/Users/stephane.liu/.dotfiles/install.sh" "/Users/stephane.liu/.install.sh"
handle_file_ln "/Users/stephane.liu/.dotfiles/p10k.zsh" "/Users/stephane.liu/.p10k.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/rcrc" "/Users/stephane.liu/.rcrc"
handle_file_ln "/Users/stephane.liu/.dotfiles/ssh/config" "/Users/stephane.liu/.ssh/config"
handle_file_ln "/Users/stephane.liu/.dotfiles/tmux/bindings.tmux" "/Users/stephane.liu/.tmux/bindings.tmux"
handle_file_ln "/Users/stephane.liu/.dotfiles/tmux/modifier.tmux" "/Users/stephane.liu/.tmux/modifier.tmux"
handle_file_ln "/Users/stephane.liu/.dotfiles/tmux/pbcopy_paste.tmux" "/Users/stephane.liu/.tmux/pbcopy_paste.tmux"
handle_file_ln "/Users/stephane.liu/.dotfiles/tmux/plugins.tmux" "/Users/stephane.liu/.tmux/plugins.tmux"
handle_file_ln "/Users/stephane.liu/.dotfiles/tmux/status_bar.tmux" "/Users/stephane.liu/.tmux/status_bar.tmux"
handle_file_ln "/Users/stephane.liu/.dotfiles/tmux/system.tmux" "/Users/stephane.liu/.tmux/system.tmux"
handle_file_ln "/Users/stephane.liu/.dotfiles/tmux/true_color_tmux_vim_support.tmux" "/Users/stephane.liu/.tmux/true_color_tmux_vim_support.tmux"
handle_file_ln "/Users/stephane.liu/.dotfiles/tmux/vi_mode.tmux" "/Users/stephane.liu/.tmux/vi_mode.tmux"
handle_file_ln "/Users/stephane.liu/.dotfiles/tmux/vim_tmux_navigator.tmux" "/Users/stephane.liu/.tmux/vim_tmux_navigator.tmux"
handle_file_ln "/Users/stephane.liu/.dotfiles/tmux/visual.tmux" "/Users/stephane.liu/.tmux/visual.tmux"
handle_file_ln "/Users/stephane.liu/.dotfiles/tmux/zsh.tmux" "/Users/stephane.liu/.tmux/zsh.tmux"
handle_file_ln "/Users/stephane.liu/.dotfiles/tool-versions" "/Users/stephane.liu/.tool-versions"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/autocmd.vim" "/Users/stephane.liu/.vim/autocmd.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/backups" "/Users/stephane.liu/.vim/backups"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/bundle" "/Users/stephane.liu/.vim/bundle"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/clipboard.vim" "/Users/stephane.liu/.vim/clipboard.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/gui.vim" "/Users/stephane.liu/.vim/gui.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/kitty.vim" "/Users/stephane.liu/.vim/kitty.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/marked_2.vim" "/Users/stephane.liu/.vim/marked_2.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/number_toggle.vim" "/Users/stephane.liu/.vim/number_toggle.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/nvim_lsp_config_solargraph.vim" "/Users/stephane.liu/.vim/nvim_lsp_config_solargraph.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/nvim_lsp_config_tw.vim" "/Users/stephane.liu/.vim/nvim_lsp_config_tw.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/options.vim" "/Users/stephane.liu/.vim/options.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/quickfix.vim" "/Users/stephane.liu/.vim/quickfix.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/ack.vim" "/Users/stephane.liu/.vim/rcplugins/ack.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/addon_mw_utils.vim" "/Users/stephane.liu/.vim/rcplugins/addon_mw_utils.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/ag.vim" "/Users/stephane.liu/.vim/rcplugins/ag.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/airline.vim" "/Users/stephane.liu/.vim/rcplugins/airline.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/ale.vim" "/Users/stephane.liu/.vim/rcplugins/ale.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/calendar.vim" "/Users/stephane.liu/.vim/rcplugins/calendar.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/camelcasemotion.vim" "/Users/stephane.liu/.vim/rcplugins/camelcasemotion.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/closetag.vim" "/Users/stephane.liu/.vim/rcplugins/closetag.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/colors.vim" "/Users/stephane.liu/.vim/rcplugins/colors.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/copilot.vim" "/Users/stephane.liu/.vim/rcplugins/copilot.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/ctrlp.vim" "/Users/stephane.liu/.vim/rcplugins/ctrlp.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/dash.vim" "/Users/stephane.liu/.vim/rcplugins/dash.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/devicons.vim" "/Users/stephane.liu/.vim/rcplugins/devicons.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/dispatch.vim" "/Users/stephane.liu/.vim/rcplugins/dispatch.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/indent_line.vim" "/Users/stephane.liu/.vim/rcplugins/indent_line.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/javascript.vim" "/Users/stephane.liu/.vim/rcplugins/javascript.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/kitty_navigator.vim" "/Users/stephane.liu/.vim/rcplugins/kitty_navigator.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/matchit.vim" "/Users/stephane.liu/.vim/rcplugins/matchit.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/misc.vim" "/Users/stephane.liu/.vim/rcplugins/misc.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/nerdtree.vim" "/Users/stephane.liu/.vim/rcplugins/nerdtree.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/nvim_lsp_config.vim" "/Users/stephane.liu/.vim/rcplugins/nvim_lsp_config.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/polyglot.vim" "/Users/stephane.liu/.vim/rcplugins/polyglot.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/prettier.vim" "/Users/stephane.liu/.vim/rcplugins/prettier.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/regex.vim" "/Users/stephane.liu/.vim/rcplugins/regex.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/scratch.vim" "/Users/stephane.liu/.vim/rcplugins/scratch.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/sessions.vim" "/Users/stephane.liu/.vim/rcplugins/sessions.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/sneak.vim" "/Users/stephane.liu/.vim/rcplugins/sneak.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/surround.vim" "/Users/stephane.liu/.vim/rcplugins/surround.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/syntastic.vim" "/Users/stephane.liu/.vim/rcplugins/syntastic.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/tabularize.vim" "/Users/stephane.liu/.vim/rcplugins/tabularize.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/taglist.vim" "/Users/stephane.liu/.vim/rcplugins/taglist.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/tasks.vim" "/Users/stephane.liu/.vim/rcplugins/tasks.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/tcomment.vim" "/Users/stephane.liu/.vim/rcplugins/tcomment.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/tlib.vim" "/Users/stephane.liu/.vim/rcplugins/tlib.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/unimpaired.vim" "/Users/stephane.liu/.vim/rcplugins/unimpaired.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/vimwiki.vim" "/Users/stephane.liu/.vim/rcplugins/vimwiki.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/xterm_color_table.vim" "/Users/stephane.liu/.vim/rcplugins/xterm_color_table.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/rcplugins/zettel.vim" "/Users/stephane.liu/.vim/rcplugins/zettel.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/session.vim" "/Users/stephane.liu/.vim/session.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/shortcuts.vim" "/Users/stephane.liu/.vim/shortcuts.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/spell.vim" "/Users/stephane.liu/.vim/spell.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/tab.vim" "/Users/stephane.liu/.vim/tab.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/undodir" "/Users/stephane.liu/.vim/undodir"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/vim-spell-en.utf-8.add" "/Users/stephane.liu/.vim/vim-spell-en.utf-8.add"
handle_file_ln "/Users/stephane.liu/.dotfiles/vim/visual.vim" "/Users/stephane.liu/.vim/visual.vim"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/after/find_cam.zsh" "/Users/stephane.liu/.zsh/after/find_cam.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/after/source_env.zsh" "/Users/stephane.liu/.zsh/after/source_env.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/aliases.zsh" "/Users/stephane.liu/.zsh/aliases.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/bat.zsh" "/Users/stephane.liu/.zsh/bat.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/before/brew_completions.zsh" "/Users/stephane.liu/.zsh/before/brew_completions.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/before/oh_my.zsh" "/Users/stephane.liu/.zsh/before/oh_my.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/brew.zsh" "/Users/stephane.liu/.zsh/brew.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/cmatrix.zsh" "/Users/stephane.liu/.zsh/cmatrix.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/command_not_found.zsh" "/Users/stephane.liu/.zsh/command_not_found.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/dip_shortcuts.zsh" "/Users/stephane.liu/.zsh/dip_shortcuts.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/docker.zsh" "/Users/stephane.liu/.zsh/docker.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/dust.zsh" "/Users/stephane.liu/.zsh/dust.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/editor.zsh" "/Users/stephane.liu/.zsh/editor.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/fd.zsh" "/Users/stephane.liu/.zsh/fd.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/functions/bcp" "/Users/stephane.liu/.zsh/functions/bcp"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/functions/bip" "/Users/stephane.liu/.zsh/functions/bip"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/functions/bup" "/Users/stephane.liu/.zsh/functions/bup"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/functions/emoji" "/Users/stephane.liu/.zsh/functions/emoji"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/functions/fif" "/Users/stephane.liu/.zsh/functions/fif"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/functions/git-churn" "/Users/stephane.liu/.zsh/functions/git-churn"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/functions/marked" "/Users/stephane.liu/.zsh/functions/marked"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/fzf.zsh" "/Users/stephane.liu/.zsh/fzf.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/gpg.zsh" "/Users/stephane.liu/.zsh/gpg.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/kitty.zsh" "/Users/stephane.liu/.zsh/kitty.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/lsd.zsh" "/Users/stephane.liu/.zsh/lsd.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/nvim.zsh" "/Users/stephane.liu/.zsh/nvim.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/path.zsh" "/Users/stephane.liu/.zsh/path.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/powerlevel10k.zsh" "/Users/stephane.liu/.zsh/powerlevel10k.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/procs.zsh" "/Users/stephane.liu/.zsh/procs.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/rcm.zsh" "/Users/stephane.liu/.zsh/rcm.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/rg.zsh" "/Users/stephane.liu/.zsh/rg.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/rtx.zsh" "/Users/stephane.liu/.zsh/rtx.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/ssh.zsh" "/Users/stephane.liu/.zsh/ssh.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/user.zsh" "/Users/stephane.liu/.zsh/user.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/vim.zsh" "/Users/stephane.liu/.zsh/vim.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zsh/z.zsh" "/Users/stephane.liu/.zsh/z.zsh"
handle_file_ln "/Users/stephane.liu/.dotfiles/zshrc" "/Users/stephane.liu/.zshrc"
