#!/bin/sh

set -e # -e: exit on error

install_dir=~/.local/share/chezmoi
unset GIT_SSL_CERT

echo $install_dir

echo "Installing homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo "Installing Homebrew packages"
brew update
brew tap homebrew/bundle
brew bundle
for brewfile in */Brewfile; do
  brew bundle --file="$brewfile"
done

export PATH=$(brew --prefix)/bin:$PATH

cd $HOME

exec chezmoi init --apply --source=$install_dir

count=0

until [ -f "$HOME/.env.private" ]; do
  if [ $count -eq 0 ]; then
    let count++
    echo "Copy .private.env from 1Password to $HOME <ENTER|(q)uit>"
    read response

    if [ "$response" = "q" ]; then
      echo "Quitting..."
      exit 0
    fi
  elif [ ! -f "$HOME/.env.private" ]; then
    echo "$HOME/.private.env could not be found. <ENTER|(q)uit>"
    read response

    if [ "$response" = "q" ]; then
      echo "Quitting..."
      exit 0
    fi
  fi
done

echo "###### TODO ######"
echo "Update .zsh/npm.zsh token from 1Password"
echo "Done!"
