#!/bin/sh

# Exits immediately on error
# set -e # disabled until script is stabilized
install_dir=$PWD
unset GIT_SSL_CERT

source $HOME/.dotfiles/bin/os_type.sh

echo "Installing Homebrew packages"
brew update
brew tap homebrew/bundle
brew bundle
for brewfile in */Brewfile; do
  brew bundle --file="$brewfile"
done

export PATH=$(brew --prefix)/bin:$PATH

# Link libpq to /usr/local/bin

# Before `rcup` runs, there is no ~/.rcrc, so we must tell `rcup` where to look.
# We need the rcrc because it tells `rcup` to ignore thousands of useless Vim
# backup files that slow it down significantly.
# Pass -v flag to run with verbose
cd $HOME

echo "Linking dotfiles into $HOME"
RCRC=$HOME/.dotfiles/rcrc rcup -f

if [ ! -d $HOME/.vim/bundle/Vundle.vim ]; then
  git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi

echo "Installing Vim packages"
vi +PluginInstall +qa

echo "Installing coc language servers"
vi +"CocInstall coc-tailwindcss coc-sh coc-solargraph coc-json coc-html coc-css coc-json" +qa

cd $HOME

if [ -d $HOME/.oh-my-zsh ]; then
  echo "Oh-my-zsh already installed"
else
  echo "Installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  echo "If changing shell (chsh) to zsh failed, sudo bash then 'chsh -s $(brew --prefix)/bin/zsh {user}'"

  echo "Installing Powerlevel9k thems for Oh-my-zsh"
  git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
fi

if [! -d $HOME/.hammerspoon/Spoons/VimMode.spoon ]; then
  #####  Hammerspoon - vim mode  #####
  echo "Configuring hammerspoon vim mode"
  bash <(curl -s https://raw.githubusercontent.com/dbalatero/VimMode.spoon/master/bin/installer)
fi

if [! -d $HOME/.hammerspoon/Spoons/SpoonInstall.spoon ]; then
  echo "Script to install Hammerspoon vim mode failed to install SpoonInstall"
  echo "See https://raw.githubusercontent.com/dbalatero/VimMode.spoon/master/bin/installer -
  bootstrap_spoon_install and use `wget -nv --no-check-certificate`"
fi

cd ${install_dir}

for setup in tag-*/setup; do
  . "$setup"
done

if [ ! -d $HOME/tmp ]; then
  echo "Creating a tmp folder in $HOME"
  mkdir $HOME/tmp
fi

echo "Setting defaults for OSX"
. ./system/osx-settings

echo "###### TODO ######"
echo "Update .zsh/npm.zsh token from 1Password"
echo "Done!"
