#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -fv -B 0 -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=1}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "mkdir $($DIRNAME "$2")"
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"

  if [ ! -e "$2" ]; then
    echo "ln failed for $2"
    exit
  fi
}
echo "*** PWD: $PWD"
echo "which ln: $(which ln)"
echo "which mkdir: $(which mkdir)"

handle_file_ln "$PWD/.dotfiles/tag-git/git-template/commit_template.txt" "$HOME/.git-template/commit_template.txt"
handle_file_ln "$PWD/.dotfiles/tag-git/git-template/hooks/lolcommits" "$HOME/.git-template/hooks/lolcommits"
handle_file_ln "$PWD/.dotfiles/tag-git/git-template/hooks/post-checkout" "$HOME/.git-template/hooks/post-checkout"
handle_file_ln "$PWD/.dotfiles/tag-git/git-template/hooks/post-commit" "$HOME/.git-template/hooks/post-commit"
handle_file_ln "$PWD/.dotfiles/tag-git/git-template/hooks/post-merge" "$HOME/.git-template/hooks/post-merge"
handle_file_ln "$PWD/.dotfiles/tag-git/git-template/hooks/post-rewrite" "$HOME/.git-template/hooks/post-rewrite"
handle_file_ln "$PWD/.dotfiles/tag-git/git-template/hooks/pre-commit" "$HOME/.git-template/hooks/pre-commit"
handle_file_ln "$PWD/.dotfiles/tag-git/git-template/hooks/pre-rebase" "$HOME/.git-template/hooks/pre-rebase"
handle_file_ln "$PWD/.dotfiles/tag-git/gitattributes" "$HOME/.gitattributes"
handle_file_ln "$PWD/.dotfiles/tag-git/gitconfig" "$HOME/.gitconfig"
handle_file_ln "$PWD/.dotfiles/tag-git/gitignore" "$HOME/.gitignore"
handle_file_ln "$PWD/.dotfiles/tag-git/vim/rcplugins/conflicted.vim" "$HOME/.vim/rcplugins/conflicted.vim"
handle_file_ln "$PWD/.dotfiles/tag-git/vim/rcplugins/endwise.vim" "$HOME/.vim/rcplugins/endwise.vim"
handle_file_ln "$PWD/.dotfiles/tag-git/vim/rcplugins/fugitive.vim" "$HOME/.vim/rcplugins/fugitive.vim"
handle_file_ln "$PWD/.dotfiles/tag-git/vim/rcplugins/gist.vim" "$HOME/.vim/rcplugins/gist.vim"
handle_file_ln "$PWD/.dotfiles/tag-git/vim/rcplugins/git.vim" "$HOME/.vim/rcplugins/git.vim"
handle_file_ln "$PWD/.dotfiles/tag-git/vim/rcplugins/gitgutter.vim" "$HOME/.vim/rcplugins/gitgutter.vim"
handle_file_ln "$PWD/.dotfiles/tag-git/vim/rcplugins/nvim_blame_line.vim" "$HOME/.vim/rcplugins/nvim_blame_line.vim"
handle_file_ln "$PWD/.dotfiles/tag-git/vim/rcplugins/vim_gh_line.vim" "$HOME/.vim/rcplugins/vim_gh_line.vim"
handle_file_ln "$PWD/.dotfiles/tag-git/zsh/after/completion.zsh" "$HOME/.zsh/after/completion.zsh"
handle_file_ln "$PWD/.dotfiles/tag-git/zsh/git.zsh" "$HOME/.zsh/git.zsh"
handle_file_ln "$PWD/.dotfiles/tag-git/zsh/lol.zsh" "$HOME/.zsh/lol.zsh"
handle_file_ln "$PWD/.dotfiles/tag-ruby/default-gems" "$HOME/.default-gems"
handle_file_ln "$PWD/.dotfiles/tag-ruby/editrc" "$HOME/.editrc"
handle_file_ln "$PWD/.dotfiles/tag-ruby/gemrc" "$HOME/.gemrc"
handle_file_ln "$PWD/.dotfiles/tag-ruby/irbrc" "$HOME/.irbrc"
handle_file_ln "$PWD/.dotfiles/tag-ruby/pryrc" "$HOME/.pryrc"
handle_file_ln "$PWD/.dotfiles/tag-ruby/railsrc" "$HOME/.railsrc"
handle_file_ln "$PWD/.dotfiles/tag-ruby/rdebugrc" "$HOME/.rdebugrc"
handle_file_ln "$PWD/.dotfiles/tag-ruby/vim/rcplugins/ale_ruby.vim" "$HOME/.vim/rcplugins/ale_ruby.vim"
handle_file_ln "$PWD/.dotfiles/tag-ruby/vim/rcplugins/bundler.vim" "$HOME/.vim/rcplugins/bundler.vim"
handle_file_ln "$PWD/.dotfiles/tag-ruby/vim/rcplugins/haml.vim" "$HOME/.vim/rcplugins/haml.vim"
handle_file_ln "$PWD/.dotfiles/tag-ruby/vim/rcplugins/projectionist.vim" "$HOME/.vim/rcplugins/projectionist.vim"
handle_file_ln "$PWD/.dotfiles/tag-ruby/vim/rcplugins/rails.vim" "$HOME/.vim/rcplugins/rails.vim"
handle_file_ln "$PWD/.dotfiles/tag-ruby/vim/rcplugins/rake.vim" "$HOME/.vim/rcplugins/rake.vim"
handle_file_ln "$PWD/.dotfiles/tag-ruby/vim/rcplugins/rspec.vim" "$HOME/.vim/rcplugins/rspec.vim"
handle_file_ln "$PWD/.dotfiles/tag-ruby/vim/rcplugins/rubocop.vim" "$HOME/.vim/rcplugins/rubocop.vim"
handle_file_ln "$PWD/.dotfiles/tag-ruby/vim/rcplugins/ruby.vim" "$HOME/.vim/rcplugins/ruby.vim"
handle_file_ln "$PWD/.dotfiles/tag-ruby/vim/rcplugins/ruby_refactoring.vim" "$HOME/.vim/rcplugins/ruby_refactoring.vim"
handle_file_ln "$PWD/.dotfiles/tag-ruby/vim/rcplugins/syntastic_ruby.vim" "$HOME/.vim/rcplugins/syntastic_ruby.vim"
handle_file_ln "$PWD/.dotfiles/tag-ruby/vim/rcplugins/vim-rspec.vim" "$HOME/.vim/rcplugins/vim-rspec.vim"
handle_file_ln "$PWD/.dotfiles/tag-ruby/vim/ruby_abbreviations.vim" "$HOME/.vim/ruby_abbreviations.vim"
handle_file_ln "$PWD/.dotfiles/tag-ruby/zsh/ruby.zsh" "$HOME/.zsh/ruby.zsh"
handle_file_ln "$PWD/.dotfiles/tag-tmux/tmux.conf" "$HOME/.tmux.conf"
handle_file_ln "$PWD/.dotfiles/tag-tmux/vim/rcplugins/tmux.vim" "$HOME/.vim/rcplugins/tmux.vim"
handle_file_ln "$PWD/.dotfiles/tag-tmux/zsh/tmux.zsh" "$HOME/.zsh/tmux.zsh"
handle_file_ln "$PWD/.dotfiles/Brewfile" "$HOME/Brewfile"
# handle_file_ln "$PWD/.dotfiles/Brewfile.lock.json" "$HOME/.Brewfile.lock.json"
handle_file_ln "$PWD/.dotfiles/agignore" "$HOME/.agignore"
handle_file_ln "$PWD/.dotfiles/bin/24-bit-colors-test.sh" "$HOME/bin/24-bit-colors-test.sh"
handle_file_ln "$PWD/.dotfiles/bin/256-colors.sh" "$HOME/bin/256-colors.sh"
handle_file_ln "$PWD/.dotfiles/bin/link_rails_intellisense" "$HOME/bin/link_rails_intellisense"
handle_file_ln "$PWD/.dotfiles/bin/plist" "$HOME/bin/plist"
handle_file_ln "$PWD/.dotfiles/bin/psgrep" "$HOME/bin/psgrep"
handle_file_ln "$PWD/.dotfiles/bin/ray" "$HOME/bin/ray"
handle_file_ln "$PWD/.dotfiles/bin/silence_ruby" "$HOME/bin/silence_ruby"
handle_file_ln "$PWD/.dotfiles/config/cheat/cheatsheets/personal/ruby" "$HOME/.config/cheat/cheatsheets/personal/ruby"
handle_file_ln "$PWD/.dotfiles/config/cheat/conf.yml" "$HOME/.config/cheat/conf.yml"
handle_file_ln "$PWD/.dotfiles/config/gitui/key_config.ron" "$HOME/.config/gitui/key_config.ron"
handle_file_ln "$PWD/.dotfiles/config/kitty/current-theme.conf" "$HOME/.config/kitty/current-theme.conf"
handle_file_ln "$PWD/.dotfiles/config/kitty/font.conf" "$HOME/.config/kitty/font.conf"
handle_file_ln "$PWD/.dotfiles/config/kitty/grab.conf" "$HOME/.config/kitty/grab.conf"
handle_file_ln "$PWD/.dotfiles/config/kitty/hints.conf" "$HOME/.config/kitty/hints.conf"
handle_file_ln "$PWD/.dotfiles/config/kitty/kitty.conf" "$HOME/.config/kitty/kitty.conf"
# handle_file_ln "$PWD/.dotfiles/config/kitty/kitty_grab/LICENSE" "$HOME/.config/kitty/kitty_grab/LICENSE"
# handle_file_ln "$PWD/.dotfiles/config/kitty/kitty_grab/_grab_ui.py" "$HOME/.config/kitty/kitty_grab/_grab_ui.py"
# handle_file_ln "$PWD/.dotfiles/config/kitty/kitty_grab/grab-vim.conf.example" "$HOME/.config/kitty/kitty_grab/grab-vim.conf.example"
# handle_file_ln "$PWD/.dotfiles/config/kitty/kitty_grab/grab.conf.example" "$HOME/.config/kitty/kitty_grab/grab.conf.example"
# handle_file_ln "$PWD/.dotfiles/config/kitty/kitty_grab/grab.py" "$HOME/.config/kitty/kitty_grab/grab.py"
# handle_file_ln "$PWD/.dotfiles/config/kitty/kitty_grab/kitten_options_definition.py" "$HOME/.config/kitty/kitty_grab/kitten_options_definition.py"
# handle_file_ln "$PWD/.dotfiles/config/kitty/kitty_grab/kitten_options_parse.py" "$HOME/.config/kitty/kitty_grab/kitten_options_parse.py"
# handle_file_ln "$PWD/.dotfiles/config/kitty/kitty_grab/kitten_options_types.py" "$HOME/.config/kitty/kitty_grab/kitten_options_types.py"
# handle_file_ln "$PWD/.dotfiles/config/kitty/kitty_grab/kitten_options_utils.py" "$HOME/.config/kitty/kitty_grab/kitten_options_utils.py"
# handle_file_ln "$PWD/.dotfiles/config/kitty/kitty_grab/kitty.conf.example" "$HOME/.config/kitty/kitty_grab/kitty.conf.example"
handle_file_ln "$PWD/.dotfiles/config/kitty/scrollback.conf" "$HOME/.config/kitty/scrollback.conf"
handle_file_ln "$PWD/.dotfiles/config/kitty/splits.conf" "$HOME/.config/kitty/splits.conf"
handle_file_ln "$PWD/.dotfiles/config/kitty/tabs.conf" "$HOME/.config/kitty/tabs.conf"
handle_file_ln "$PWD/.dotfiles/config/kitty/theme.conf" "$HOME/.config/kitty/theme.conf"
handle_file_ln "$PWD/.dotfiles/config/kitty/themes/solarized-dark.conf" "$HOME/.config/kitty/themes/solarized-dark.conf"
handle_file_ln "$PWD/.dotfiles/config/kitty/themes/solarized-light.conf" "$HOME/.config/kitty/themes/solarized-light.conf"
handle_file_ln "$PWD/.dotfiles/config/kitty/visual.conf" "$HOME/.config/kitty/visual.conf"
handle_file_ln "$PWD/.dotfiles/config/nvim/init.vim" "$HOME/.config/nvim/init.vim"
handle_file_ln "$PWD/.dotfiles/config/tmuxinator/cc.yml" "$HOME/.config/tmuxinator/cc.yml"
handle_file_ln "$PWD/.dotfiles/ctags" "$HOME/.ctags"
handle_file_ln "$PWD/.dotfiles/dir_colors" "$HOME/.dir_colors"
handle_file_ln "$PWD/.dotfiles/inputrc" "$HOME/.inputrc"
handle_file_ln "$PWD/.dotfiles/install.sh" "$HOME/.install.sh"
handle_file_ln "$PWD/.dotfiles/p10k.zsh" "$HOME/.p10k.zsh"
handle_file_ln "$PWD/.dotfiles/rcrc" "$HOME/.rcrc"
handle_file_ln "$PWD/.dotfiles/ssh/config" "$HOME/.ssh/config"
handle_file_ln "$PWD/.dotfiles/tmux/bindings.tmux" "$HOME/.tmux/bindings.tmux"
handle_file_ln "$PWD/.dotfiles/tmux/modifier.tmux" "$HOME/.tmux/modifier.tmux"
handle_file_ln "$PWD/.dotfiles/tmux/pbcopy_paste.tmux" "$HOME/.tmux/pbcopy_paste.tmux"
handle_file_ln "$PWD/.dotfiles/tmux/plugins.tmux" "$HOME/.tmux/plugins.tmux"
handle_file_ln "$PWD/.dotfiles/tmux/status_bar.tmux" "$HOME/.tmux/status_bar.tmux"
handle_file_ln "$PWD/.dotfiles/tmux/system.tmux" "$HOME/.tmux/system.tmux"
handle_file_ln "$PWD/.dotfiles/tmux/true_color_tmux_vim_support.tmux" "$HOME/.tmux/true_color_tmux_vim_support.tmux"
handle_file_ln "$PWD/.dotfiles/tmux/vi_mode.tmux" "$HOME/.tmux/vi_mode.tmux"
handle_file_ln "$PWD/.dotfiles/tmux/vim_tmux_navigator.tmux" "$HOME/.tmux/vim_tmux_navigator.tmux"
handle_file_ln "$PWD/.dotfiles/tmux/visual.tmux" "$HOME/.tmux/visual.tmux"
handle_file_ln "$PWD/.dotfiles/tmux/zsh.tmux" "$HOME/.tmux/zsh.tmux"
handle_file_ln "$PWD/.dotfiles/tool-versions" "$HOME/.tool-versions"
handle_file_ln "$PWD/.dotfiles/vim/autocmd.vim" "$HOME/.vim/autocmd.vim"
handle_file_ln "$PWD/.dotfiles/vim/backups" "$HOME/.vim/backups"
handle_file_ln "$PWD/.dotfiles/vim/bundle" "$HOME/.vim/bundle"
handle_file_ln "$PWD/.dotfiles/vim/clipboard.vim" "$HOME/.vim/clipboard.vim"
handle_file_ln "$PWD/.dotfiles/vim/gui.vim" "$HOME/.vim/gui.vim"
handle_file_ln "$PWD/.dotfiles/vim/kitty.vim" "$HOME/.vim/kitty.vim"
handle_file_ln "$PWD/.dotfiles/vim/marked_2.vim" "$HOME/.vim/marked_2.vim"
handle_file_ln "$PWD/.dotfiles/vim/number_toggle.vim" "$HOME/.vim/number_toggle.vim"
handle_file_ln "$PWD/.dotfiles/vim/nvim_lsp_config_solargraph.vim" "$HOME/.vim/nvim_lsp_config_solargraph.vim"
handle_file_ln "$PWD/.dotfiles/vim/nvim_lsp_config_tw.vim" "$HOME/.vim/nvim_lsp_config_tw.vim"
handle_file_ln "$PWD/.dotfiles/vim/options.vim" "$HOME/.vim/options.vim"
handle_file_ln "$PWD/.dotfiles/vim/quickfix.vim" "$HOME/.vim/quickfix.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/ack.vim" "$HOME/.vim/rcplugins/ack.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/addon_mw_utils.vim" "$HOME/.vim/rcplugins/addon_mw_utils.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/ag.vim" "$HOME/.vim/rcplugins/ag.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/airline.vim" "$HOME/.vim/rcplugins/airline.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/ale.vim" "$HOME/.vim/rcplugins/ale.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/calendar.vim" "$HOME/.vim/rcplugins/calendar.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/camelcasemotion.vim" "$HOME/.vim/rcplugins/camelcasemotion.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/closetag.vim" "$HOME/.vim/rcplugins/closetag.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/colors.vim" "$HOME/.vim/rcplugins/colors.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/copilot.vim" "$HOME/.vim/rcplugins/copilot.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/ctrlp.vim" "$HOME/.vim/rcplugins/ctrlp.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/dash.vim" "$HOME/.vim/rcplugins/dash.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/devicons.vim" "$HOME/.vim/rcplugins/devicons.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/dispatch.vim" "$HOME/.vim/rcplugins/dispatch.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/indent_line.vim" "$HOME/.vim/rcplugins/indent_line.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/javascript.vim" "$HOME/.vim/rcplugins/javascript.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/kitty_navigator.vim" "$HOME/.vim/rcplugins/kitty_navigator.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/matchit.vim" "$HOME/.vim/rcplugins/matchit.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/misc.vim" "$HOME/.vim/rcplugins/misc.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/nerdtree.vim" "$HOME/.vim/rcplugins/nerdtree.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/nvim_lsp_config.vim" "$HOME/.vim/rcplugins/nvim_lsp_config.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/polyglot.vim" "$HOME/.vim/rcplugins/polyglot.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/prettier.vim" "$HOME/.vim/rcplugins/prettier.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/regex.vim" "$HOME/.vim/rcplugins/regex.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/scratch.vim" "$HOME/.vim/rcplugins/scratch.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/sessions.vim" "$HOME/.vim/rcplugins/sessions.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/sneak.vim" "$HOME/.vim/rcplugins/sneak.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/surround.vim" "$HOME/.vim/rcplugins/surround.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/syntastic.vim" "$HOME/.vim/rcplugins/syntastic.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/tabularize.vim" "$HOME/.vim/rcplugins/tabularize.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/taglist.vim" "$HOME/.vim/rcplugins/taglist.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/tasks.vim" "$HOME/.vim/rcplugins/tasks.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/tcomment.vim" "$HOME/.vim/rcplugins/tcomment.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/tlib.vim" "$HOME/.vim/rcplugins/tlib.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/unimpaired.vim" "$HOME/.vim/rcplugins/unimpaired.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/vimwiki.vim" "$HOME/.vim/rcplugins/vimwiki.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/xterm_color_table.vim" "$HOME/.vim/rcplugins/xterm_color_table.vim"
handle_file_ln "$PWD/.dotfiles/vim/rcplugins/zettel.vim" "$HOME/.vim/rcplugins/zettel.vim"
handle_file_ln "$PWD/.dotfiles/vim/session.vim" "$HOME/.vim/session.vim"
handle_file_ln "$PWD/.dotfiles/vim/shortcuts.vim" "$HOME/.vim/shortcuts.vim"
handle_file_ln "$PWD/.dotfiles/vim/spell.vim" "$HOME/.vim/spell.vim"
handle_file_ln "$PWD/.dotfiles/vim/tab.vim" "$HOME/.vim/tab.vim"
handle_file_ln "$PWD/.dotfiles/vim/undodir" "$HOME/.vim/undodir"
handle_file_ln "$PWD/.dotfiles/vim/vim-spell-en.utf-8.add" "$HOME/.vim/vim-spell-en.utf-8.add"
handle_file_ln "$PWD/.dotfiles/vim/visual.vim" "$HOME/.vim/visual.vim"
handle_file_ln "$PWD/.dotfiles/zsh/after/find_cam.zsh" "$HOME/.zsh/after/find_cam.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/after/source_env.zsh" "$HOME/.zsh/after/source_env.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/aliases.zsh" "$HOME/.zsh/aliases.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/bat.zsh" "$HOME/.zsh/bat.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/before/brew_completions.zsh" "$HOME/.zsh/before/brew_completions.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/before/oh_my.zsh" "$HOME/.zsh/before/oh_my.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/brew.zsh" "$HOME/.zsh/brew.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/cmatrix.zsh" "$HOME/.zsh/cmatrix.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/command_not_found.zsh" "$HOME/.zsh/command_not_found.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/dip_shortcuts.zsh" "$HOME/.zsh/dip_shortcuts.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/docker.zsh" "$HOME/.zsh/docker.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/dust.zsh" "$HOME/.zsh/dust.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/editor.zsh" "$HOME/.zsh/editor.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/fd.zsh" "$HOME/.zsh/fd.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/functions/bcp" "$HOME/.zsh/functions/bcp"
handle_file_ln "$PWD/.dotfiles/zsh/functions/bip" "$HOME/.zsh/functions/bip"
handle_file_ln "$PWD/.dotfiles/zsh/functions/bup" "$HOME/.zsh/functions/bup"
handle_file_ln "$PWD/.dotfiles/zsh/functions/emoji" "$HOME/.zsh/functions/emoji"
handle_file_ln "$PWD/.dotfiles/zsh/functions/fif" "$HOME/.zsh/functions/fif"
handle_file_ln "$PWD/.dotfiles/zsh/functions/git-churn" "$HOME/.zsh/functions/git-churn"
handle_file_ln "$PWD/.dotfiles/zsh/functions/marked" "$HOME/.zsh/functions/marked"
handle_file_ln "$PWD/.dotfiles/zsh/fzf.zsh" "$HOME/.zsh/fzf.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/gpg.zsh" "$HOME/.zsh/gpg.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/kitty.zsh" "$HOME/.zsh/kitty.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/lsd.zsh" "$HOME/.zsh/lsd.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/nvim.zsh" "$HOME/.zsh/nvim.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/path.zsh" "$HOME/.zsh/path.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/powerlevel10k.zsh" "$HOME/.zsh/powerlevel10k.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/procs.zsh" "$HOME/.zsh/procs.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/rcm.zsh" "$HOME/.zsh/rcm.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/rg.zsh" "$HOME/.zsh/rg.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/rtx.zsh" "$HOME/.zsh/rtx.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/ssh.zsh" "$HOME/.zsh/ssh.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/user.zsh" "$HOME/.zsh/user.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/vim.zsh" "$HOME/.zsh/vim.zsh"
handle_file_ln "$PWD/.dotfiles/zsh/z.zsh" "$HOME/.zsh/z.zsh"
handle_file_ln "$PWD/.dotfiles/zshrc" "$HOME/.zshrc"
