#!/usr/bin/env ruby

spec_hits = []
# Find all filenames in spec directory that have been (A)dded (C)opied or (M)odified
filenames = `git diff --cached --name-only --diff-filter=ACM`.split("\n")

filenames.each do |filename|
  if filename.end_with? '_spec.rb' 
    file_changes = `git diff --cached #{filename}`
    results = `#{file_changes} | grep \^+\[\^+\] | grep focus`
    spec_hits.push filename if $? == 0 # $? - status of last external process run

    results = `#{file_changes} | grep \^+\[\^+\] | grep binding.pry`
    spec_hits.push filename if $? == 0 # $? - status of last external process run
  end
end

if spec_hits.any?
  #puts "\e[33m>>> Please remove your `focus: true` from the following tests before committing\e[0m"
  # 31m - Red
  # 32m - Green
  # 33m - Yellow
  # 34m - Blue
  # 35m - Purple
  # 36m - Cyan
  # 37m - White
  # bold - prepend 1; ie - 1;35m
  # underline - prepend 4;
  # background - 40m - 47m
  #
  # 0m - reset 
  puts "\e[1;37m\e[41m>>> Commit Aborted! Remove `focus or binding.pry` from the following specs \e[0m"
  puts spec_hits.join("\n")

  exit 1
end
