# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    prme: pr list --author "@me" --state "all" --limit "10000"
    cr: pr list --search "review:required draft:false author:allindow author:chadwilken author:charlieharris author:DustinFisher author:EdwardBarton author:florasaramago author:groovestation31785 author:jeffmcfadden author:johncocam author:mjmelnick author:PelagicDev author:pkccgh author:sdfreund10 author:slvdrog author:stephaneliu author:timross14 author:zaydion" --json number,author,title,url,headRefName,updatedAt --template '{{range .}}{{tablerow (printf "#%v" .number | autocolor "green") .author.login .title (.headRefName | autocolor "yellow") (timeago .updatedAt) .url}}{{end}}'
    prc: pr create -l "Group:\ Communication" --assignee stephaneliu --reviewer "CompanyCam/backend-engineers"
    prd: pr create -l "Group:\ Communication" --assignee stephaneliu --draft
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
