alias 'ps?'='procs | ag '
alias ..="cd .."
alias :q="exit"
alias gg='clear'
alias inet='ifconfig | grep inet'
alias nc='nocorrect'
alias q='exit'
alias terminal-notifier='reattach-to-user-namespace terminal-notifier'
alias which="which -a"
