# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="sliu"
# ZSH_THEME="robbyrussell"
# ZSH_THEME="blinks"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# plugins=(colored-man code-dir command-not-found chucknorris docker git git-flow history-substring-search tmuxinator vi-mode web-search z)
plugins=(colored-man bundler code-dir command-not-found git history-substring-search vi-mode taskwarrior web-search z chucknorris)

is_osx() {
  [ "$(uname -s)" = Darwin ]
}

is_linux() {
  [ "$(uname -s)" = Linux ]
}

source $ZSH/oh-my-zsh.sh

# Force 256 color support see:
# http://www.enigmacurry.com/2009/01/20/256-colors-on-the-linux-terminal/
# export TERM=xterm-256color
export TERM=screen-256color

source /$HOME/.zsh_aliases
if is_linux; then
  source .zsh_aliases_linux
fi

export PATH=./bin:/home/sliu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:$PATH

# export USE_BUNDLER=force
export EDITOR=nvim
export VISUAL=vim

if [[ -e "$HOME/bin/jre1.7.0_45" ]]
then
  export JAVA_HOME=$HOME/bin/jre1.7.0_45
fi

bindkey -M viins 'jk' vi-cmd-mode
bindkey -M viins 'kj' vi-cmd-mode

# bind k and j for VI mode to history search
# Type a letter/word, jk (escape), j or k (search)
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# ANSI Colors
# export BLACK='\033[0;30m' # doesn't work well with solarize
# USAGE: printf "I ${LTRED}heart ${RED}Ruby\n"
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export BROWN='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LTGRAY='\033[0;37m'
# export DKGRAY='\033[1;30m' # doesn't work well with solarize
export LTRED='\033[1;31m'
# export LTGREEN='\033[1;32m' # doesn't work well with solarize
# export YELLOW='\033[1;33m' # doesn't work well with solarize
# export LTBLUE='\033[1;34m' # doesn't work well with solarize
export LTPURPLE='\033[1;35m'
# export LTCYAN='\033[1;36m' # doesn't work well with solarize
export WHITE='\033[1;37m'
export NC='\033[0m'

export DYLD_LIBRARY_PATH=/usr/local/lib:$DLYD_LIBRARY_PATH
# export SSL_CERT_FILE=/usr/local/etc/openssl/certs/cert.pem

### Added by the Heroku Toolbelt
#export PATH="/usr/local/heroku/bin:$PATH"

source /usr/local/share/chruby/chruby.sh

export DOCKER_HOST=tcp://localhost:4243

# Prevent tmux sessions from renaming pane title
export DISABLE_AUTO_TITLE=true
export AUTO_TITLE=false

# default ruby
chruby ruby-2.3.3

chuck_cow

# add color to directories
eval `dircolors ~/dircolors.256dark`
# added by travis gem
[ -f /Users/sliu/.travis/travis.sh ] && source /Users/sliu/.travis/travis.sh
# use commands:
# enable_cac_enabled_git and disable_cac_enabled_git to toggle feature
if [[ -e "$HOME/cac-enabled-git-env.sh" ]]
then
  . "/$HOME/cac-enabled-git-env.sh"
  disable_cac_aware_git
fi

platform=`uname`
if [[ $platform  == 'Linux' ]]; then
  source /usr/share/autojump/autojump.zsh
fi

eval "$(direnv hook zsh)"
source $HOME/bin/ruby_switcher.sh

export LD_LIBRARY_PATH=~/lib/x86_64-linux-gnu
# Display result of last AV scan
if [[ -e "/usr/local/uvscan/report.sh" ]]
then
  /usr/local/uvscan/report.sh
fi
