# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"
#ZSH_THEME="sliu"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# plugins=(colored-man code-dir command-not-found chucknorris docker git git-flow history-substring-search tmuxinator vi-mode web-search z)
plugins=(colored-man code-dir command-not-found docker git git-flow history-substring-search tmuxinator vi-mode web-search z)

source $ZSH/oh-my-zsh.sh

# Force 256 color support see:
# http://www.enigmacurry.com/2009/01/20/256-colors-on-the-linux-terminal/
# export TERM=xterm-256color
export TERM=screen-256color

source /$HOME/.zsh_aliases
export PATH=./bin:/home/sliu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:$PATH
[[ -s "$HOME/.tmuxinator/scripts/tmuxinator" ]] && source $HOME/.tmuxinator/scripts/tmuxinator

# export USE_BUNDLER=force
export EDITOR=vim
export VISUAL=vim

if [[ -e "$HOME/bin/jre1.7.0_45" ]]
then
  export JAVA_HOME=$HOME/bin/jre1.7.0_45
fi

bindkey -M viins 'jk' vi-cmd-mode
bindkey -M viins 'kj' vi-cmd-mode

# ANSI Colors
# export BLACK='\033[0;30m' # doesn't work well with solarize
# USAGE: printf "I ${LTRED}heart ${RED}Ruby\n"
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export BROWN='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LTGRAY='\033[0;37m'
# export DKGRAY='\033[1;30m' # doesn't work well with solarize
export LTRED='\033[1;31m'
# export LTGREEN='\033[1;32m' # doesn't work well with solarize
# export YELLOW='\033[1;33m' # doesn't work well with solarize
# export LTBLUE='\033[1;34m' # doesn't work well with solarize
export LTPURPLE='\033[1;35m'
# export LTCYAN='\033[1;36m' # doesn't work well with solarize
export WHITE='\033[1;37m'
export NC='\033[0m'

# export SSL_CERT_FILE=/usr/local/etc/openssl/certs/cert.pem

### Added by the Heroku Toolbelt
#export PATH="/usr/local/heroku/bin:$PATH"

# Removed in favor of envrc
# See github.com/zimbatm/direnv
# eval "$(direnv hook zsh)"

source /usr/local/share/chruby/chruby.sh

export DOCKER_HOST=tcp://localhost:4243

# default ruby
chruby ruby-2.2.2

# chuck_cow

eval "$(direnv hook zsh)"

