name: Test

on:
  push:
    paths-ignore:
      - "README.md"
      - ".github/**"
      - "hooks/**"
      - "system/**"
  workflow_dispatch:

jobs:
  test:
    env:
    runs-on: macos-latest

    steps:
      - run: echo "Roof roof."
