name: Test

on:
  push:
    paths-ignore:
  workflow_dispatch:

jobs:
  test:
    env:
      TEST: true
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with: .dotfiles
      - run: ./install
