name: Test install script

on:
  push:
    paths-ignore:
      - "README.md"
      - "hooks/**"
      - "system/**"
      - "Brewfile"
      - "utils/**"
      - "ssh/**"
      - "hooks/**"
      - "bin/**"
  workflow_dispatch:

jobs:
  test:
    env:
      TEST: true
    runs-on: macos-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          path: '.dotfiles'
      - name: Perform install
        run: ./.dotfiles/test/runner
